name: MSBuild

on:
  pull_request:
    types: [synchronize, opened]
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        
      - run: |
          msbuild -version
        
      - name: nuget restore
        run: nuget restore X1Fold_LaptopSwitcher.sln
        shell: cmd
          
      - name: MSBuild
        run: msbuild X1Fold_LaptopSwitcher.sln -p:OutDir="out/";Configuration=Release;Platform="x64"
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: build-result
          path: ./laptopswitcher/out/
